[project]
name = "bitcoin-dao"
description = 'Bitcoin Layer 2 DAO fork of Executor DAO'
authors = ['mijoco']
telemetry = false
cache_dir = '.cache'

[[project.requirements]]
contract_id = 'SP3JP0N1ZXGASRJ0F7QAHWFPGTVK9T2XNXDB908Z.proposal-trait'

[[project.requirements]]
contract_id = 'SP3JP0N1ZXGASRJ0F7QAHWFPGTVK9T2XNXDB908Z.extension-trait'

[[project.requirements]]
contract_id = 'SP3JP0N1ZXGASRJ0F7QAHWFPGTVK9T2XNXDB908Z.ownable-trait'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'

[[project.requirements]]
contract_id = 'ST1NXBK3K5YYMD6FD41MVNP3JS1GABZ8TRVX023PT.sip-010-trait-ft-standard'

[contracts.proposal-trait]
path = "contracts/traits/proposal-trait.clar"
clarity_version = 2
epoch = 2.3

[contracts.ownable-trait]
path = "contracts/traits/ownable-trait.clar"
clarity_version = 2
epoch = 2.3

[contracts.sip010-ft-trait]
path = "contracts/traits/sip010-ft-trait.clar"
clarity_version = 2
epoch = 2.3

[contracts.extension-trait]
path = "contracts/traits/extension-trait.clar"
clarity_version = 2
epoch = 2.3

[contracts.bitcoin-dao]
path = "contracts/bitcoin-dao.clar"
clarity_version = 2
epoch = 2.3

[contracts.bde000-governance-token]
path = "contracts/extensions/bde000-governance-token.clar"
clarity_version = 2
epoch = 2.3

[contracts.bde001-proposal-voting]
path = "contracts/extensions/bde001-proposal-voting.clar"
clarity_version = 2
epoch = 2.3

[contracts.bde002-proposal-submission]
path = "contracts/extensions/bde002-proposal-submission.clar"
clarity_version = 2
epoch = 2.3

[contracts.bde003-emergency-proposals]
path = "contracts/extensions/bde003-emergency-proposals.clar"
clarity_version = 2
epoch = 2.3

[contracts.bde004-emergency-execute]
path = "contracts/extensions/bde004-emergency-execute.clar"
clarity_version = 2
epoch = 2.3

[contracts.bde005-dev-fund]
path = "contracts/extensions/bde005-dev-fund.clar"
clarity_version = 2
epoch = 2.3

[contracts.governance-token-trait]
path = "contracts/traits/governance-token-trait.clar"
clarity_version = 2
epoch = 2.3

[contracts.nft-escrow]
path = "contracts/external/nft-escrow.clar"
clarity_version = 2
epoch = 2.3
